services:
  - type: web
    name: childcare-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application