# Generated by Django 3.1 on 2022-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_invoice_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='saturdaycare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='weddingcare',
            field=models.IntegerField(default=0),
        ),
    ]
