# Generated by Django 3.1 on 2022-06-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220610_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='parttime',
            new_name='partday',
        ),
    ]
