# Generated by Django 3.1 on 2022-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220610_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='weddingcare',
            new_name='cosycorner',
        ),
        migrations.AddField(
            model_name='pricing',
            name='nonsupervised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='supervised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='weddingnanny',
            field=models.IntegerField(default=0),
        ),
    ]
