# Generated by Django 3.1 on 2022-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220611_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='parttimeretainer',
            new_name='partdayretainer',
        ),
    ]
