# Generated by Django 3.1 on 2022-07-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20220718_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='month',
            field=models.CharField(default='', max_length=64),
        ),
    ]
