# Generated by Django 3.1 on 2022-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_purchase_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='taxyear',
            field=models.CharField(default='', max_length=64),
        ),
    ]
