# Generated by Django 3.1 on 2022-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220801_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
