# Generated by Django 3.1 on 2022-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_child_invoicesub'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
