# Generated by Django 3.1 on 2022-08-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_child_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
